name: test

on:
  push:
    branches: ['dev']
    paths-ignore:
      - 'README.md'
      - 'Dockerfile'
      - 'docker-compose.yml'
  workflow_dispatch:
jobs:
  windows:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          ref: 'dev'
      - name: Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.68.0
            override: true
      - uses: lukka/get-cmake@latest
      - name: setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: 'a7b6122f6b6504d16d96117336a0562693579933'
      - name: Cache Openssl
        id: cache-openssl
        uses: actions/cache@v3
        with:
          path: C:\vcpkg\packages\
          key: ${{ runner.os }}-openssl-static-2
      - name: Install Openssl
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        run: |
          vcpkg install openssl:x64-windows-static
      - uses: actions/cache@v3
        id: cache-cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/
            ~/.cargo/git/
            target/
          key: ${{ runner.os }}-cargo
      - name: Test
        env:
          OPENSSL_DIR: C:\vcpkg\packages\openssl_x64-windows-static
          OPENSSL_INCLUDE_DIR: C:\vcpkg\packages\openssl_x64-windows-static\include
          OPENSSL_LIB_DIR: C:\vcpkg\packages\openssl_x64-windows-static\lib
          OPENSSL_STATIC: Yes
          OPENSSL_NO_VENDOR: 1
          COS_REGION: chengdu
          COS_APP_SECERT: ${{ secrets.COS_APP_SECERT }}
          COS_APP_ID: ${{ secrets.COS_APP_ID }}
          COS_BUCKET_ID: ${{ secrets.COS_BUCKET_ID }}
          LFS_USERNAME: ${{ secrets.COS_BUCKET_ID }}
          LFS_PASSWORD: ${{ secrets.LFS_PASSWORD }}
          RUST_LOG: debug
          RUST_BACKTRACE: 1
        run: | 
          cargo test --all-features -- --show-output
  linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          ref: 'dev'
      - name: Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.68.0
            override: true
      - uses: actions/cache@v3
        id: cache-cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/
            ~/.cargo/git/
            target/
          key: ${{ runner.os }}-cargo
      - name: Test
        env:
          COS_REGION: chengdu
          COS_APP_SECERT: ${{ secrets.COS_APP_SECERT }}
          COS_APP_ID: ${{ secrets.COS_APP_ID }}
          COS_BUCKET_ID: ${{ secrets.COS_BUCKET_ID }}
          LFS_USERNAME: ${{ secrets.COS_BUCKET_ID }}
          LFS_PASSWORD: ${{ secrets.LFS_PASSWORD }}
          RUST_LOG: debug
          RUST_BACKTRACE: 1
        run: | 
          cargo test --all-features -- --show-output
